#!/bin/bash

# (C) Libor Spacek, 2019

# usage: quotes file format
# reads any plain text (or markdown) from file, e.g., mynovel.md
# writes to disk stylised and converted file.format, eg. mynovel.doc
# requires a Unix/Linux type system with sed and pandoc installed
# target output format will be typically odt or doc required by publishers
# it is passed to pandoc so you can try any other pandoc formats

# Changes all "straight" 'computer' quotes to properly stylised ones.
# Assumes that all opening quotes are preceded by a white space.

# also converts -- to endash, --- to emdash, ... to ellipsis

# todo: downgrading nested double quotes to singles.
# For now, explicitly deploy single quotes inside double ones.

# Example usage: quotes-en mynovel.md doc

PROGN=${0##*/}
if [ $# -ne 2 ]; then
  printf 1>&2 "$PROGN expects two arguments, file.ext targetformat\n"
  exit 2
fi
FILE=$1
FMT=$2
if ! [ -f "$FILE" ]; then
  printf 1>&2 "$PROGN quitting, file $FILE not found!\n"
  exit 2
fi 
parts=(${FILE//./ })  # parses the filename to replace the extension

if [ ${parts[-1]} == $FMT ]; then
  printf "$PROGN detected same output extension! Backing up $FILE as %s \n\
before overwriting with the new version.\n" ${parts[-2]}.bak
  cp $FILE ${parts[-2]}.bak
fi

sed -e 's_--_–_g' -e 's_---_—_g' -e 's_\.\.\._\…_g' \
	-e 's_^"_“_g' -e "s_^'_‘_g" -e 's_\([[:space:]]\)"_\1“_g' -e 's_"_”_g' \
	-e "s_\([[:space:]]\)'_\1‘_g" -e "s_'_’_g" < $FILE | pandoc -o ${parts[-2]}.$FMT
	
printf "$PROGN written ${parts[-2]}.$FMT to the current directory\n"

