#!/bin/bash

# (C) Libor Spacek, 2019

# usage: uvozovky file format
# reads any plain text (or markdown) from file, e.g., mynovel.md
# writes to disk stylised and converted file.format, eg. mynovel.doc
# requires a Unix/Linux type system with sed and pandoc installed
# target output format will be typically odt or doc required by publishers
# it is passed to pandoc so you can try any other pandoc formats

# Changes all "straight" 'computer' quotes to properly stylised Czech ones.
# Assumes that all (lower) opening quotes are preceded by a white space or newline
# ´something´ (enclosing accents = čárky) are changed to double arrow (french) quotes: »something«

# also converts -- to endash, --- to emdash, ... to ellipsis

# todo: downgrading nested double quotes to singles.
# For now, explicitly deploy single quotes inside double ones.

# Example usage: uvozovky mynovel.md doc

PROGN=${0##*/}
if [ $# -ne 2 ]; then
  printf 1>&2 "$PROGN očekávají dva parametry, soubor.ext cílovýformát\n"
  exit 2
fi
FILE=$1
FMT=$2
if ! [ -f "$FILE" ]; then
  printf 1>&2 "$PROGN končí, soubor $FILE nenalezen!\n"
  exit 2
fi 
parts=(${FILE//./ })  # parses the filename to replace the extension

if [ ${parts[-1]} == $FMT ]; then
  printf "$PROGN objevily již existující soubor výstupu!\n$FILE založen jako ${parts[-2]}.bak a přepsán novou verzí.\n" 
  cp $FILE ${parts[-2]}.bak
fi

sed -e 's_--_–_g' -e 's_---_—_g' -e 's_\.\.\._\…_g' \
	-e 's_^"_„_g' -e "s_^'_‚_g" -e 's_^´\([^[:space:]]\)_»\1_g' \
	-e 's_\([[:space:]]\)"_\1„_g' -e 's_"_“_g' \
	-e 's_\([[:space:]]\)´\([^[:space:]]\)_\1»\2_g' -e 's_\([^[:space:]]\)´_\1«_g' \
	-e "s_\([[:space:]]\)'_\1‚_g" -e "s_'_‘_g" < $FILE | pandoc -o ${parts[-2]}.$FMT
	
printf "$PROGN zapsaly typograficky upravený soubor ${parts[-2]}.$FMT do místního adresáře\n"

